:datasett: NVDB Vegnett Pluss
:kortnavn: NVDBVegnettPluss
:versjon: 1.0
:skjemaversjon: {versjon}
:underversjon: 2024-02-01
:publisert: 2024-02-14
:metadata-url: https://kartkatalog.geonorge.no/metadata/
:dokumentstatus: 2
// All informasjon i hode over denne linja må fylles ut for hvert datasett. Øvrige parametere settes i adoc_parametere.adoc
include::inkluder/filhode.adoc[]

== Innledning, historikk og endringslogg

=== Innledning

NVDB Vegnett Pluss er i hovedsak et forvaltningsdatasett for kommunene til forvaltning av vegnettet i SFKB. En kvalitetssikret versjon tilgjengeliggjøres på Geonorge. Datasettet omfatter alle kjørbare veger som er lengre enn 50 meter, eller del av et nettverk, samt gang- og sykkelveger og sykkelveger representert som veglenkegeometri. Fortau, gangveger, gangfelt, traktorveger og stier som tidligere fantes i FKB-TraktorvegSti, vil også være en del av NVDB Vegnett Pluss. For disse typene veg gjenstår noe innsamling av data.

I tillegg inneholder datasettet adresseinformasjon (som gir mulighet for kobling til matrikkelen og andre registre), fartsgrenser, trafikkreguleringer, trafikkrestriksjoner og vegklasser. Veglenkens attributter er tematisert etter typeveg, vegkategori og vegfase.  

* Typeveg: bilferje, enkel bilveg, fortau, gangfelt, gang- og sykkelveg, gangveg, gatetun, gågate, kanalisert veg (kjørebane og kjørefelt), passasjerferje, rampe, rundkjøring, sykkelveg og trapp.
* Vegkategori: europa- (E), riks- (R), fylkes- (F), kommunal veg (K), privat veg (P) og skogsveg (S).
* Vegfase: eksisterende veg (V), under bygging (A). 

NVDB Vegnett Pluss er et produkt som eksporteres fra Nasjonal vegdatabank (NVDB). Grunnlagsdataene ajourholdes av Statens vegvesen og Kartverket. Les mer om denne på:  https://www.vegvesen.no/fag/teknologi/nasjonal-vegdatabank/[Nasjonal vegdatabank (NVDB) | Statens vegvesen] +

I tillegg til NVDB Vegnett Pluss finnes det også et forenklet datasett, NVDB Vegnett. Dette datasettet består av de samme veglenkene og vegsperringene vi finner i NVDB Vegnett Pluss. +

Europa-, riks- og fylkesvegnettet ajourføres kontinuerlig i NVDB med basis i Statens vegvesens plan- og ferdigvegsdata. Ajourføring av kommunale, private og skogsveger organiseres gjennom Norge digitalt og FDV-avtalene med kommuner, administrert av Kartverket. 


Denne produktspesifikasjonen er utarbeidet iht. SOSI produktspesifikasjoner – Krav og godkjenning 5.0 <<SOSI-KRAV>>. UML-modellen som ligger til grunn for innhold i diagrammene og dokumentasjon i kap. 5, følger reglene i SOSI Regler for UML-modellering, versjon 5.1 <<SOSI-UML>>. http://sosi.geonorge.no/veiledere/UML[Denne veilederen] gir hjelp til å lese UML-diagrammene.

=== Historikk

Elveg 2.0 var en videreutvikling og sammenslåing av FKB-Vegnett 4.03, Vbase og Elveg, hvor det for første gang ble innført lineært refererte objekter. Fortau, gangveger og gangfelt skulle også overføres fra FKB Traktorveg/Sti. NVDB Vegnett Pluss er en revisjon av Elveg 2.0 etter at datasettet nå har fått endret formål til å være et forvaltningsdatasett mot kommunene.


=== Endringslogg

Første versjon



=== Normative referanser

include::inkluder/kap14_normativ_ref.adoc[]

<<<

== Definisjoner og forkortelser

=== Definisjoner

include::inkluder/kap21_definisjoner.adoc[]

=== Forkortelser

include::inkluder/kap22_forkortelser.adoc[]

<<<

== Generelt om spesifikasjonen

=== Unik identifisering
NVDBVegnettPlus

==== Fullstendig navn
{datasett} 

==== Versjon
{versjon}

=== Referansedato
2024-02-01

=== Ansvarlig organisasjon
Kartverket

=== Språk
Norsk

=== Hovedtema
Basisdata, Samferdsel

=== Temakategori
basisData

=== Sammendrag

NVDB Vegnett Pluss er et vegnettsdatasett som omfatter alle kjørbare veger og vegnett for gående og syklende, i den grad dette er registrert, representert som veglenkegeometri. I tillegg inneholder datasettet adresseinformasjon (som gir mulighet for kobling til matrikkelen og andre registre), fartsgrenser, trafikkreguleringer, trafikkrestriksjoner og vegklasser, alle representert som egengeometri. 


=== Formål

NVDB Vegnett Pluss brukes som forvaltningsdatasett i den offentlige forvaltningen av vegnett gjennom Geovekst FDV-avtalene.


// Fellesdel som dekker kap 3.9 - 3.12 for alle FKB-produktspesifikasjoner
include::inkluder/kap39-312_representasjon.adoc[]

=== Supplerende beskrivelse
Data ikke angitt

<<<

== Spesifikasjonsomfang

include::inkluder/kap4_omfang.adoc[]  

<<<

== Innhold og struktur

=== Omfang
<<HeleDatasettet,Hele datasettet>>

include::modellRapport.adoc[leveloffset=+1]

<<<

== Referansesystem

include::inkluder/kap6_referansesystem.adoc[]

<<<

== Kvalitet

=== Omfang
Hele datasettet

==== Fullstendighet
Datasettet er fullstendig så langt det er mulig og oppdateres kontinuerlig i henhold til avtaler om forvaltning, drift og vedlikehold.

==== Stedfestingsnøyaktighet
Det er et overordnet prinsipp at best tilgjengelige geometri skal benyttes i vegnettet. 
NVDB Vegnett Pluss  inneholder ikke homogene data. Produktet som helhet kan ikke love bedre kvalitet enn de dårligste datakildene. Vegen registreres så langt mulig i tre dimensjoner (nord, øst, høyde), men ved administrativ datafangst godkjennes 2D data (digitalisering fra ortofoto) dersom andre datakilder ikke finnes.

NVDB Vegnett Pluss inneholder detaljerte data stort sett registrert fotogrammetrisk fra flybilder med en oppløsing mellom 7 og 25 cm. Nøyaktigheten varierer fra +/- 0.10 m til +/- 2 m avhengig av objekttype, områdetype og datafangstmetode.

==== Egenskapsnøyaktighet
Egenskaper stedfestes med bakgrunn fra administrativt ajourhold og følger generelt samme krav som øvrige kvalitetskrav. 

==== Tidfestingsnøyaktighet
Kontinuerlig ajourhold.

==== Logisk konsistens
Kontinuerlig kontroll. 

<<<

== Datafangst

NVDB Vegnett Pluss er et direkte uttrekk fra NVDB. Vegnett i NVDB er etablert med data fra vegsituasjon (fotogrammetri), GPS og treghetsmålinger, administrativ ajourhold (gjennom ajourhold av NVDB Vegnett Pluss) og med data fra Statens vegvesens plan- og ferdigvegsdata. 

I tillegg mottar Kartverket og Statens vegvesen feilmeldinger og endringer fra publikum gjennom deres feilmeldingstjenester http://rettikartet.no[http://rettikartet.no] og https://fiksvegdata.atlas.vegvesen.no/[fiksvegdata.atlas.vegvesen.no]. Disse meldingene kan etter en vurdering mot andre datakilder bli lagt inn i NVDB og kommer deretter ut i NVDB Vegnett Pluss. 


<<<

== Datavedlikehold


=== Vedlikeholdsinformasjon - Kartleggingsprosjekt

==== Omfang 
Hele datasettet

==== Vedlikeholdsfrekvens 
Kontinuerlig

==== Vedlikeholdsbeskrivelse 
Fotogrammetrisk ajourhold utføres gjennom Geovekst kartleggingsprosjekter. Kartleggingsprosjektene spesifiseres og finansieres gjennom Geovekst og settes ut på anbud fra Kartverket. Flyfotografering og selve det fotogrammetriske ajourholdet utføres av et privat firma i tråd med fotogrammetrisk registreringsinstruks. Kartverket gjør kontroll av leveranse ved mottak og legger dataene inn i databasen i samarbeid med Statens vegvesen.

=== Vedlikeholdsinformasjon – Avtaler om forvaltning, drift og vedlikehold
==== Omfang 
Hele datasettet

==== Vedlikeholdsfrekvens 
Kontinuerlig

==== Vedlikeholdsbeskrivelse 
Det er i regi av Geovekst inngått avtaler om forvaltning, drift og vedlikehold (FDV) med de fleste kommuner. Her avtalefestes oppgaver og finansiering av et felles kontinuerlig ajourhold av FKB-dataene blant partene i avtalen (dette gjelder også for NVDB Vegnett Pluss). 
Den viktigste parten i avtalene er kommunen da mange av endringene i FKB kan fanges opp gjennom kommunal saksbehandling. 
Dataene blir så sendt til Kartverket for innlesing i databasen. 
Kommuner utenfor Geovekst gjør tilsvarende vedlikehold i egen regi og leverer data i henhold til Norge digitalt avtale.

==== Omfang 
Hele datasettet

==== Vedlikeholdsfrekvens 
Kontinuerlig

==== Vedlikeholdsbeskrivelse 
Statens vegvesen er forpliktet til å levere ferdigvegsdata til NVDB Vegnett Pluss ved ferdigstillelse av prosjekter.

=== Vedlikeholdsinformasjon – Feilmeldinger og avvikshåndtering
==== Omfang 
Hele datasettet

==== Vedlikeholdsfrekvens 
Kontinuerlig

==== Vedlikeholdsbeskrivelse 
Kartverket og Statens vegvesen mottar feilmeldinger fra publikum gjennom deres feilmeldingstjenester http://rettikartet.no/ og https://fiksvegdata.atlas.vegvesen.no/ . Disse meldingene kan etter en vurdering mot andre datakilder bli lagt inn i NVDB (og deretter komme ut i NVDB Vegnett Pluss). 


<<<

== Presentasjon

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Referanse til presentasjonskatalog
Det er utarbeidet en presentasjonsregel for Elveg, men ikke for NVDB Vegnett Pluss enda. Denne er tilgjengelig via geonorge:
https://register.geonorge.no/register/versjoner/tegneregler/kartverket/elveg

<<<

== Leveranse

include::inkluder/kap11_leveranse.adoc[]

<<<

== Tilleggsinformasjon
Ingen angitt informasjon

== Metadata

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Metadataspesifikasjon

include::inkluder/kap13_metadata.adoc[]

<<<

[appendix]
== GML-realisering

GML-realiseringen følger kravene i "Realisering i GML-format 5.0" <<SOSI-GML>>. Realiseringen defineres av følgende filer:

* {skjema-url}/NVDBVegnettPlus.xsd[GML-Skjema]
* {skjema-url}/NVDBVegnettPlus.sch[Schematron-Skjema]


[appendix]
== SOSI-format-realisering

SOSI-realiseringen følger kravene i "Realisering i SOSI-format 5.0" <<SOSI-FORMAT>>. Under en utlisting av SOSI-formatrealiseringen:

include::vedlegg.adoc[]

:sectnums!:

<<<

[discrete]
== Lisensvilkår

// Inkl. lisensvilkår
include::inkluder/lisensvilkaar.adoc[]